function Hd = FIRChebysevHP
%FIRCHEBYSEVHP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 21-Dec-2017 13:21:49

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 500;  % Sampling Frequency

N             = 500;        % Order
Fc            = 4;          % Cutoff Frequency
flag          = 'noscale';  % Sampling Flag
SidelobeAtten = 100;        % Window Parameter

% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
